### ISSUE TITLE
Get Back Up and Running 

### ISSUE THREAD

**Issue by dan-fritchman** [BWRC-AMS-ML-Discovery/AutoCkt#1]
Step 1 for this repo was: rip it into 3 separate Python packages: `Auto`, `Ckt`, and `Shared`, with the intent that the former two can run on isolated machines. 

Step 2: get that up and running!

**Comment by wayne-wang-1119** [comment]
fixed new instructions and setup now in different parts, moving on to make it more like "client or server sides" differentiable services that faces clients
