### ISSUE TITLE
Next Circuits

### ISSUE THREAD

**Issue by dan-fritchman** [BWRC-AMS-ML-Discovery/AutoCkt#13]
Potential next circuits to optimize: 

* Latch 
* Flip-Flop
* StrongArm Comparator
* Oscillators, ring and/or LC
* Ring amp 
* Current DAC
* LDO regulator 
* Bandgap reference
* Some fancier flavor of opamp, e.g. that pursued by BagNET
* The optical front-end, also via BagNET

The task: identify which to pursue, and then design generators for them.

**Comment by dan-fritchman** [comment]
Links to the papers referenced: 

* https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9576505
* https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8942062
* https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9576505
* https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9116513
* https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9116200

**Comment by dan-fritchman** [comment]
Another helpful source of potential inspiration:  
https://github.com/ALIGN-analoglayout/ALIGN-public/tree/master/examples

**Comment by kingh0730** [comment]
Closing this, because we moved this issue to https://github.com/BWRC-AMS-ML-Discovery/BwrcAmsMlDiscovery/issues/22

**Comment by uduse** [comment]
@kingh0730 is this a private repo? I can't access the link 🤔

**Comment by kingh0730** [comment]
> Closing this, because we moved this issue to [BWRC-AMS-ML-Discovery/BwrcAmsMlDiscovery#22](https://github.com/BWRC-AMS-ML-Discovery/BwrcAmsMlDiscovery/issues/22)

Yeah, currently it's private. @dan-fritchman When do we want to make the other repo public?
