### ISSUE TITLE
Upgrades dependencies throughout

### ISSUE THREAD

**Issue by dan-fritchman** [BWRC-AMS-ML-Discovery/AutoCkt#2]
In total we've got this list of external dependencies: 

```python
[
        "numpy==1.16.4",
        "scipy==1.1.0",
        "gym==0.10.5", # Core ML dependency: OpenAI Gym
        "ray==0.6.3", # Ray for RL, parallelization, training
        "ipython==6.5.0", # FIXME: probably dev only? 
        "pyyaml==5.1.2",
]
```

Most are pretty old.  
Let's get all of these to, like, "kinda compatible with the current versions". 

Then, our most important dependency:  
This combination pins us to Python3.5.  

Getting our client-server content included will require using at least 3.7, preferably the current versions (3.10-3.11).

**Comment by wayne-wang-1119** [comment]
Upgraded to work under 3.7, same as authentication, can upgrade to 3.10, will do so later since now figured out how to it's not difficult, moving onto assigning storage for diff users on disk for ownership problem
