### ISSUE TITLE
Roll in Library-ized `Discovery`

### ISSUE THREAD

**Issue by dan-fritchman** [BWRC-AMS-ML-Discovery/AutoCkt#6]
The `AutoCkt` side of https://github.com/BWRC-AMS-ML-Discovery/BwrcAmsMlDiscovery/issues/2. 

`AutoCkt` should look a lot like the `Example` directory in `BwrcAmsMlDiscovery`.

**Comment by kingh0730** [comment]
Done in the afore mentioned PR
