### ISSUE TITLE
Hdl21-Based Sims/ Measurements

### ISSUE THREAD

**Issue by dan-fritchman** [BWRC-AMS-ML-Discovery/AutoCkt#9]
Task: port the simulations & measurements into `hdl21.sim`. 

These should produce the `AutoCktOutput` type expected by the ML client. 

Assignee: @HarryYanH

**Comment by dan-fritchman** [comment]
Numpy stuff to help extract measurements: 

* Absolute value/ magnitude, array-wide - https://numpy.org/doc/stable/reference/generated/numpy.absolute.html
* Crossing (zero) index - https://stackoverflow.com/a/3843124/11193687

Also - how does the existing AutoCkt code do it? 
Please compare against that.

**Comment by HarryYanH** [comment]
Thank you.

**Comment by kingh0730** [comment]
Closing this because issue moved to https://github.com/BWRC-AMS-ML-Discovery/BwrcAmsMlDiscovery/issues/23
